name: lint - type - test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install requirements/ci.txt
        python -m pip install requirements/package.txt
    - name: Lint
      run: |
        ruff check .
    - name: Type
      run: |
        mypy src/llm-index
    - name: Test
      run: |
        pytest
